### ISSUE TITLE
the brute is stuck 

### ISSUE THREAD

**Issue by xxnbyy** [jordanpotti/AWSBucketDump#12]
I use the normal command " python AWSBucketDump.py -l BucketNames.txt -g interesting_Keywords.txt -D -m 500000 -d 1" and start brute,but it will stuck suddenly ,and there is many errors like this 

`Traceback (most recent call last):
  File "AWSBucketDump.py", line 45, in bucket_worker
    fetch(item)
  File "AWSBucketDump.py", line 33, in fetch
    response = requests.get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='ample.s3.amazonaws.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5c3735e550>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPConnectionPool(host='ample.s3.amazonaws.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5c3735e550>: Failed to establish a new connection: [Errno 111] Connection refused',))
`

How could i fix this?

**Comment by jordanpotti** [comment]
Try to run it with python3.
